### ISSUE TITLE
iPhoneXS Maxでツイートボタンが表示されない

### ISSUE THREAD

**Issue by fumimaker** [sfc-tlab/reiwa_bustimer#26]
iPhoneXS MaxでBustimerを見るとツイートボタンが表示されないようです。
Safariからもローカルでも見えないみたいです。
![IMG_8273](https://user-images.githubusercontent.com/25518367/60650523-46f4e300-9e7f-11e9-993a-192259c1e9a2.PNG)
![IMG_8274](https://user-images.githubusercontent.com/25518367/60650524-46f4e300-9e7f-11e9-88df-252804a33781.PNG)

**Comment by Im-neko** [comment]
iphoneX MAXの実機safariでしか再現しなくて泣きそう

iphoneX MAX持ってる誰か氏デバッグしてくれると嬉しい....

**Comment by fumimaker** [comment]
デバッグってどんなことすればいいんですか？

**Comment by Im-neko** [comment]
スマホとmacをusbで繋いでスマホでbustimer開いた時のコンソールログ見てみるとか??

実際に触って色々見てみるしかないからデバッグできそうな誰かにお願いしたみが...
そもそも他のiPhoneXS Maxでも再現するか分からんからまずその確認からというのもある!!

**Comment by fumimaker** [comment]
原因わかりました。これ、AddBrockerのせいみたいです...。ご迷惑をおかけしました
