### ISSUE TITLE
CSS書く

### ISSUE THREAD

**Issue by Im-neko** [sfc-tlab/reiwa_bustimer#3]

**Comment by atsukoba** [comment]
CSS書く時ってどういう作業の流れで開発してますか？

**Comment by atsukoba** [comment]
というのも，`docker-compose up -d`してlocalhost:{$FRONT_PORT} でローカルのサーバにアクセスできると思うんですが，吐かれたhtmlに対して一度css書いて，それを`styled-components`の形に分割していくという感じですかね…？(全く分からない)

**Comment by Im-neko** [comment]
@atsukoba 
おおおお、みてなかった申し訳ない！！！
基本的に開発時は`npm run dev`で立ち上げて見ながら開発をしていて、これだとホットリロードされるので直接ソースコード書きながらリアルタイムに変更が反映されるのでその状態で開発してってますん！！！
ちなみにfeature/cssブランチで作っていってるので何か書いてくれたりしたらこのブランチにプルリク出す形でオナシャス！
あと、デザインも一応少しずつ作ってはいるので参考にしてください！
https://xd.adobe.com/spec/2cba0d1d-054d-4cb0-56ec-9546d1024843-5a8b/

**Comment by atsukoba** [comment]
ありがとうございます！見てみます

**Comment by Im-neko** [comment]
そろそろええんちゃう？
