### ISSUE TITLE
読み込みが遅いことについて

### ISSUE THREAD

**Issue by konbu310** [sfc-tlab/reiwa_bustimer#32]
という話を聞いて見にきました。

ふと思ったのですが、Nex.jsを使用しているならば同社が提供している[now](https://now.sh)というホスティングサービスを使用してみたら如何でしょうか？
カスタムドメインもいけたきがします。たぶん...

実際にcloneして試しにデプロイしてみましたが、だいぶ早くなりました。
https://reiwa-bustimer-clone.now.sh/

（やんごとなき理由があってこうしているのであればすみません😇）

**Comment by Im-neko** [comment]
issueありがとうございます！！！

恥ずかしながらnowの存在を知らずにやっていました()
とはいえ何かしらのホスティングサービスを使うのも手なのですが，採用しなかった理由としては以下の理由があります．
・元々の古いbustimerが研究会で管理しているサーバで稼働していた(なのでそのまま研究会のサーバで動かしている)
・研究会のサーバがあまり使われていなかったので使っている
・研究会メンバーのwebサービスのオペレーティングの勉強用にも汎用的な構成にしたい
ということがありました！

ただ，実際に試していただいた物を見た感じ，now使った時の旨味が上記の理由よりも圧倒的に大きいと判断したので是非使わせていただきたく思います！

ありがとうございます！！！

**Comment by konbu310** [comment]
Nowすごいのでぜひ！！
()

**Comment by konbu310** [comment]
わざわざ理由までありがとうございます🙇‍♂️
デプロイ含めだいぶ凝ってたのでやろうと思えば何でもできるんだろうな感は感じてました()

Nowはよくできる子なのでぜひ使ってあげてください！
思いつきでissue書いてみてよかったです。

**Comment by Im-neko** [comment]
nowめっちゃ簡単で速いしで感動して早速切り替えてしまいましたwww

速度面はずっと気になっていたので助かりました！
ありがとうございます！
